# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BPT_RealmModel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '~> 4.1.0'
  pod 'SwiftyJSON'
  
  target 'BPT_RealmModelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BPT_RealmModelUITests' do
    # Pods for testing
  end

end
